Data Wrangling, I
Perform the following operations using Python on any open source dataset (e.g., data.csv)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear
 description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas dataframe.
4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking
the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the
data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
In addition to the codes and outputs, explain every operation that you do in the above steps and
explain everything that you do to import/read/scrape the data set.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("A1_data.csv")

In [3]:
df.head()

,Election Year,Expert ID,State,Sex,Age Range,Politician,Candidate,Activist,Monitor,Election Official,...,Electoral Authorities Index,Election Rigged,Deadlines Restrictive,Voters Waited,Voters Intimidated,Multiple Ballots Cast,Machines Accurate,Records Secure,Votes Counted Quickly,Outcome Reflected Popular Will
0,2016,1,Alabama,Male,50-59,NaN,NaN,NaN,NaN,NaN,...,68.75,Disagree,Disagree,Strongly Agree,Don't Know,Don't Know,Agree,Don't Know,Agree,Disagree
1,2016,2,Alabama,Male,60-69,NaN,NaN,NaN,NaN,NaN,...,56.25,Strongly Disagree,Agree,Neither Agree Nor Disagree,Neither Agree Nor Disagree,Strongly Disagree,Agree,Don't Know,Agree,Agree
2,2016,3,Alabama,Male,60-69,NaN,NaN,NaN,NaN,NaN,...,62.50,Disagree,Disagree,Agree,Disagree,Don't Know,Neither Agree Nor Disagree,Neither Agree Nor Disagree,Strongly Agree,Neither Agree Nor Disagree
3,2016,4,Alabama,Male,50-59,NaN,NaN,NaN,NaN,NaN,...,75.00,Disagree,Strongly Agree,Strongly Agree,Don't Know,Disagree,Agree,Agree,Agree,Strongly Disagree
4,2016,5,Alabama,Male,40-49,NaN,NaN,NaN,NaN,NaN,...,74.06,Disagree,Disagree,Disagree,Disagree,Strongly Disagree,Agree,Agree,Strongly Agree,Strongly Agree

In [4]:
df.tail()

,Election Year,Expert ID,State,Sex,Age Range,Politician,Candidate,Activist,Monitor,Election Official,...,Electoral Authorities Index,Election Rigged,Deadlines Restrictive,Voters Waited,Voters Intimidated,Multiple Ballots Cast,Machines Accurate,Records Secure,Votes Counted Quickly,Outcome Reflected Popular Will
721,2016,722,Wyoming,Male,60-69,NaN,NaN,NaN,NaN,NaN,...,75.31,Strongly Disagree,Strongly Disagree,Don't Know,Don't Know,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree
722,2016,723,Wyoming,Male,70-79,NaN,NaN,NaN,NaN,NaN,...,75.00,Strongly Disagree,Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree
723,2016,724,Wyoming,Female,60-69,NaN,NaN,NaN,NaN,NaN,...,72.81,Strongly Disagree,Disagree,Don't Know,Disagree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Agree
724,2016,725,Wyoming,Male,40-49,NaN,NaN,NaN,NaN,NaN,...,93.75,Strongly Disagree,Agree,Strongly Agree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Not Applicable
725,2016,726,Wyoming,Male,40-49,NaN,NaN,NaN,NaN,NaN,...,81.25,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree

In [5]:
df.isnull().sum()

Election Year                     0
Expert ID                         0
State                             0
Sex                               0
Age Range                         0
                                 ..
Multiple Ballots Cast             2
Machines Accurate                 2
Records Secure                    3
Votes Counted Quickly             0
Outcome Reflected Popular Will    1
Length: 85, dtype: int64

In [6]:
df.describe()

,Election Year,Expert ID,Politician,Candidate,Activist,Monitor,Election Official,Voter,Political Scale,Perceptions of Electoral Integrity Index,...,Election Procedures Index,Voting District Boundaries Index,Voter Registration Index,Party/Candidate Registration Index,Media Coverage Index,Campaign Finance Index,Voting Process Index,Vote Count Index,Election Results Index,Electoral Authorities Index
count,726.0,726.000000,6.0,3.0,9.0,4.0,11.0,637.0,718.000000,715.000000,...,724.000000,723.000000,717.000000,722.000000,722.000000,718.000000,719.000000,716.000000,721.000000,721.000000
mean,2016.0,363.500000,1.0,1.0,1.0,1.0,1.0,1.0,3.362117,62.501692,...,78.649959,29.090636,55.884393,73.227839,52.045720,51.169624,68.157079,78.296047,61.800069,73.380166
std,0.0,209.722436,0.0,0.0,0.0,0.0,0.0,0.0,1.538828,10.998161,...,18.373292,24.986580,16.203786,17.609712,17.140193,17.937146,11.599253,12.420314,12.122071,18.830607
min,2016.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,15.310000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25.000000,15.000000,22.500000,0.000000
25%,2016.0,182.250000,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,55.205000,...,68.750000,8.330000,47.500000,64.000000,40.000000,39.812500,61.800000,72.000000,56.250000,62.500000
50%,2016.0,363.500000,1.0,1.0,1.0,1.0,1.0,1.0,3.000000,62.240000,...,75.000000,25.000000,55.830000,75.000000,54.500000,51.125000,68.750000,76.250000,62.500000,75.000000
75%,2016.0,544.750000,1.0,1.0,1.0,1.0,1.0,1.0,4.000000,70.540000,...,93.750000,41.670000,64.170000,85.000000,65.000000,65.000000,76.090000,88.000000,68.750000,82.500000
max,2016.0,726.000000,1.0,1.0,1.0,1.0,1.0,1.0,10.000000,89.900000,...,100.000000,100.000000,100.000000,100.000000,95.000000,100.000000,96.880000,100.000000,100.000000,100.000000

In [7]:
df.shape

(726, 85)

In [8]:
df.dtypes

Election Year                      int64
Expert ID                          int64
State                             object
Sex                               object
Age Range                         object
                                   ...
Multiple Ballots Cast             object
Machines Accurate                 object
Records Secure                    object
Votes Counted Quickly             object
Outcome Reflected Popular Will    object
Length: 85, dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 726 entries, 0 to 725
Data columns (total 85 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Election Year                             726 non-null    int64
 1   Expert ID                                 726 non-null    int64
 2   State                                     726 non-null    object
 3   Sex                                       726 non-null    object
 4   Age Range                                 726 non-null    object
 5   Politician                                6 non-null      float64
 6   Candidate                                 3 non-null      float64
 7   Activist                                  9 non-null      float64
 8   Monitor                                   4 non-null      float64
 9   Election Official                         11 non-null     float64
 10  Voter                                     637 non-null    float64
 11  Citizen                                   705 non-null    object
 12  Political Scale                           718 non-null    float64
 13  Candidate Supported                       618 non-null    object
 14  Perceptions of Electoral Integrity Index  715 non-null    float64
 15  State Electoral Integrity                 720 non-null    float64
 16  National Electoral Integrity              723 non-null    float64
 17  Laws Discriminated                        725 non-null    object
 18  Laws Favored Incumbent                    725 non-null    object
 19  Laws Restricted Citizen Rights            726 non-null    object
 20  Electoral Laws Index                      696 non-null    float64
 21  Election Managed Well                     725 non-null    object
 22  Voting Information Available              724 non-null    object
 23  Election Officials Fair                   725 non-null    object
 24  Election Followed Law                     726 non-null    object
 25  Election Procedures Index                 724 non-null    float64
 26  Boundaries Discriminated                  726 non-null    object
 27  Boundaries Favored Incumbent              726 non-null    object
 28  Boundaries Impartial                      724 non-null    object
 29  Voting District Boundaries Index          723 non-null    float64
 30  Citizens Not Found in Register            725 non-null    object
 31  Register Inaccurate                       725 non-null    object
 32  Ineligible Voters Registered              725 non-null    object
 33  Voter Registration Index                  717 non-null    float64
 34  Opposition Prevented                      725 non-null    object
 35  Women Provided Opportunity                726 non-null    object
 36  Leaders Selected Candidates               726 non-null    object
 37  Campaign Rallies Restricted               725 non-null    object
 38  Party/Candidate Registration Index        722 non-null    float64
 39  Newspapers Balanced                       725 non-null    object
 40  Television Favored Incumbent              725 non-null    object
 41  Media Access Fair                         724 non-null    object
 42  Media Coverage Fair                       725 non-null    object
 43  Social Media Exposed Fraud                724 non-null    object
 44  Media Coverage Index                      722 non-null    float64
 45  Subsidy Access Fair                       724 non-null    object
 46  Donation Access Fair                      726 non-null    object
 47  Campaign Accounts Transparent             726 non-null    object
 48  Elections Bought by Rich                  725 non-null    object
 49  Resources Improperly Used                 725 non-null    object
 50  Campaign Finance Index                    718 non-null    float64
 51  Voters Threatened with Violence           725 non-null    object
 52  Fradulent Votes Cast                      725 non-null    object
 53  Voting Process Easy                       725 non-null    object
 54  Choice of Candidates                      724 non-null    object
 55  Postal Ballots Available                  723 non-null    object
 56  Disabled Provided Access                  724 non-null    object
 57  Expatriates Able to Vote                  721 non-null    object
 58  Internet Ballots Available                723 non-null    object
 59  Voting Process Index                      719 non-null    float64
 60  Ballot Boxes Secure                       725 non-null    object
 61  Results Announced Without Delay           726 non-null    object
 62  Vote Count Fair                           724 non-null    object
 63  International Monitors Restricted         726 non-null    object
 64  Domestic Monitors Restricted              725 non-null    object
 65  Vote Count Index                          716 non-null    float64
 66  Results Challenged                        724 non-null    object
 67  Protests Peaceful                         724 non-null    object
 68  Protests Violent                          724 non-null    object
 69  Dispute Resolved in Courts                725 non-null    object
 70  Election Results Index                    721 non-null    float64
 71  Authorities Impartial                     725 non-null    object
 72  Information Distributed                   724 non-null    object
 73  Authorities Scrutinized                   725 non-null    object
 74  Authorities Performed Well                725 non-null    object
 75  Electoral Authorities Index               721 non-null    float64
 76  Election Rigged                           725 non-null    object
 77  Deadlines Restrictive                     724 non-null    object
 78  Voters Waited                             726 non-null    object
 79  Voters Intimidated                        724 non-null    object
 80  Multiple Ballots Cast                     724 non-null    object
 81  Machines Accurate                         724 non-null    object
 82  Records Secure                            723 non-null    object
 83  Votes Counted Quickly                     726 non-null    object
 84  Outcome Reflected Popular Will            725 non-null    object
dtypes: float64(21), int64(2), object(62)
memory usage: 482.2+ KB

In [10]:
df_encoded = pd.get_dummies(df , columns = ["Sex"] , dtype = int)

In [11]:
df

,Election Year,Expert ID,State,Sex,Age Range,Politician,Candidate,Activist,Monitor,Election Official,...,Electoral Authorities Index,Election Rigged,Deadlines Restrictive,Voters Waited,Voters Intimidated,Multiple Ballots Cast,Machines Accurate,Records Secure,Votes Counted Quickly,Outcome Reflected Popular Will
0,2016,1,Alabama,Male,50-59,NaN,NaN,NaN,NaN,NaN,...,68.75,Disagree,Disagree,Strongly Agree,Don't Know,Don't Know,Agree,Don't Know,Agree,Disagree
1,2016,2,Alabama,Male,60-69,NaN,NaN,NaN,NaN,NaN,...,56.25,Strongly Disagree,Agree,Neither Agree Nor Disagree,Neither Agree Nor Disagree,Strongly Disagree,Agree,Don't Know,Agree,Agree
2,2016,3,Alabama,Male,60-69,NaN,NaN,NaN,NaN,NaN,...,62.50,Disagree,Disagree,Agree,Disagree,Don't Know,Neither Agree Nor Disagree,Neither Agree Nor Disagree,Strongly Agree,Neither Agree Nor Disagree
3,2016,4,Alabama,Male,50-59,NaN,NaN,NaN,NaN,NaN,...,75.00,Disagree,Strongly Agree,Strongly Agree,Don't Know,Disagree,Agree,Agree,Agree,Strongly Disagree
4,2016,5,Alabama,Male,40-49,NaN,NaN,NaN,NaN,NaN,...,74.06,Disagree,Disagree,Disagree,Disagree,Strongly Disagree,Agree,Agree,Strongly Agree,Strongly Agree
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,2016,722,Wyoming,Male,60-69,NaN,NaN,NaN,NaN,NaN,...,75.31,Strongly Disagree,Strongly Disagree,Don't Know,Don't Know,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree
722,2016,723,Wyoming,Male,70-79,NaN,NaN,NaN,NaN,NaN,...,75.00,Strongly Disagree,Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree
723,2016,724,Wyoming,Female,60-69,NaN,NaN,NaN,NaN,NaN,...,72.81,Strongly Disagree,Disagree,Don't Know,Disagree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Agree
724,2016,725,Wyoming,Male,40-49,NaN,NaN,NaN,NaN,NaN,...,93.75,Strongly Disagree,Agree,Strongly Agree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Not Applicable
725,2016,726,Wyoming,Male,40-49,NaN,NaN,NaN,NaN,NaN,...,81.25,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree

In [12]:
df_encoded

,Election Year,Expert ID,State,Age Range,Politician,Candidate,Activist,Monitor,Election Official,Voter,...,Deadlines Restrictive,Voters Waited,Voters Intimidated,Multiple Ballots Cast,Machines Accurate,Records Secure,Votes Counted Quickly,Outcome Reflected Popular Will,Sex_Female,Sex_Male
0,2016,1,Alabama,50-59,NaN,NaN,NaN,NaN,NaN,1.0,...,Disagree,Strongly Agree,Don't Know,Don't Know,Agree,Don't Know,Agree,Disagree,0,1
1,2016,2,Alabama,60-69,NaN,NaN,NaN,NaN,NaN,1.0,...,Agree,Neither Agree Nor Disagree,Neither Agree Nor Disagree,Strongly Disagree,Agree,Don't Know,Agree,Agree,0,1
2,2016,3,Alabama,60-69,NaN,NaN,NaN,NaN,NaN,1.0,...,Disagree,Agree,Disagree,Don't Know,Neither Agree Nor Disagree,Neither Agree Nor Disagree,Strongly Agree,Neither Agree Nor Disagree,0,1
3,2016,4,Alabama,50-59,NaN,NaN,NaN,NaN,NaN,1.0,...,Strongly Agree,Strongly Agree,Don't Know,Disagree,Agree,Agree,Agree,Strongly Disagree,0,1
4,2016,5,Alabama,40-49,NaN,NaN,NaN,NaN,NaN,NaN,...,Disagree,Disagree,Disagree,Strongly Disagree,Agree,Agree,Strongly Agree,Strongly Agree,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,2016,722,Wyoming,60-69,NaN,NaN,NaN,NaN,NaN,NaN,...,Strongly Disagree,Don't Know,Don't Know,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,0,1
722,2016,723,Wyoming,70-79,NaN,NaN,NaN,NaN,NaN,1.0,...,Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,0,1
723,2016,724,Wyoming,60-69,NaN,NaN,NaN,NaN,NaN,1.0,...,Disagree,Don't Know,Disagree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,1,0
724,2016,725,Wyoming,40-49,NaN,NaN,NaN,NaN,NaN,1.0,...,Agree,Strongly Agree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Not Applicable,0,1
725,2016,726,Wyoming,40-49,NaN,NaN,NaN,NaN,NaN,1.0,...,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,0,1

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
encoder = OneHotEncoder(handle_unknown="ignore" , sparse_output=False)

In [15]:
encoded = encoder.fit_transform(df[["Sex"]])

In [16]:
encoded   #it will give the numpy array not a dataframe

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], shape=(726, 2))